In [1]:
import numpy as np

In [2]:
A = np.array([[1,2], [3,4]])
A.shape

(2, 2)

In [3]:
B = np.array([[5,6], [7,8]])
B.shape

(2, 2)

In [4]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [5]:
np.dot(B, A)

array([[23, 34],
       [31, 46]])

In [6]:
C = np.array([[1,2,3], [4,5,6]])
C.shape

(2, 3)

In [7]:
D = np.array([[1,2], [3,4], [5,6]])
D.shape

(3, 2)

In [11]:
np.dot(D, C)

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

In [12]:
np.dot(C, D)

array([[22, 28],
       [49, 64]])