In [7]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))

In [8]:
X = np.array([1.0, 0.5])
W1 = np.array([[0.1, 0.3, 0.5], [0.2, 0.4, 0.6]])
B1 = np.array([0.1, 0.2, 0.3])
print(W1.shape) # (2, 3)
print(X.shape) # (2,)
print(B1.shape) # (3,)

(2, 3)
(2,)
(3,)


In [9]:
A1 = np.dot(X, W1) + B1
A1

array([0.3, 0.7, 1.1])

In [10]:
A1.shape

(3,)

In [12]:
Z1 = sigmoid(A1)
print(A1) # [0.3, 0.7, 1.1]
print(Z1) # [0.57444252, 0.66818777, 0.75026011]

[0.3 0.7 1.1]
[0.57444252 0.66818777 0.75026011]


In [13]:
W2 = np.array([[0.1, 0.4], [0.2, 0.5], [0.3, 0.6]])
B2 = np.array([0.1, 0.2])

In [14]:
print(Z1.shape) # (3,)
print(W2.shape) # (3, 2)
print(B2.shape) # (2,)

(3,)
(3, 2)
(2,)


In [15]:
A2 = np.dot(Z1, W2) + B2
Z2 = sigmoid(A2)

In [17]:
print(A2)
print(Z2)

[0.51615984 1.21402696]
[0.62624937 0.7710107 ]


In [19]:
def identity_function(x):
    return x

In [20]:
W3 = np.array([[0.1, 0.3], [0.2, 0.4]])
B3 = np.array([0.1, 0.2])

In [21]:
A3 = np.dot(Z2, W3) + B3
Y = identity_function(A3) # 或者Y = A3

In [22]:
print(A3)

[0.31682708 0.69627909]


In [23]:
print(Y)

[0.31682708 0.69627909]
